### ISSUE TITLE
incorrect file name for `[`

### ISSUE THREAD

**Issue by vbatts** [archiecobbs/mtree-port#8]
Description:
in directory hierarchy specification, the entry for `/usr/bin/[` is incorrectly recorded as `\133`.

Actual Results:
```
# ./usr/bin
bin             type=dir mode=0555 nlink=2 size=20480 \
                time=1461191900.000000000
    \133        size=41448 time=1455637743.000000000
```

Expected results:
```
# ./usr/bin
bin             type=dir mode=0555 nlink=2 size=20480 \
                time=1461191900.000000000
    [        size=41448 time=1455637743.000000000
```

Coincidentally, mtree is able to validate the specification. But https://github.com/vbatts/go-mtree fails with `2016/06/26 14:40:58 lstat usr/bin/\133: no such file or directory`

Version of mtree: 373706c7e6c83c95df2655c464f63002c448df39

The environment variables while producing the manifest were:
```
TERM=linux
LC_ALL=en_US.utf-8
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
LANG=en_US.utf-8
DISPLAY=:0
COLORTERM=truecolor
XAUTHORITY=/run/user/1000/gdm/Xauthority
MAIL=/var/mail/root
LOGNAME=root
USER=root
USERNAME=root
HOME=/root
SHELL=/bin/bash
SUDO_COMMAND=/usr/bin/env
SUDO_USER=vbatts
SUDO_UID=1000
SUDO_GID=1000
```

**Comment by archiecobbs** [comment]
I don't think this is a bug, but rather a misunderstanding of the syntax of `mtree` output files.

`mtree` encodes "funny" characters in filenames using the `vis(3)` function and decodes them using `unvis(3)` (versions of both of these functions are included in the source). This ensures that `mtree` files only contain printable characters, regardless of the names of the listed files, which in UNIX can contain arbitrary byte values (other than nul and forward slash).

What you are seeing is an octal-encoded version of the string `[`. This is expected behavior.

**Comment by vbatts** [comment]
Good to know. I'll fix this on my side.
